apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proj.fullname" . }}
data:
  # Backend Settings
  PYTHONUNBUFFERED: "0"
  ALLOWED_HOSTS: {{ .Values.application.allowedHosts | quote }}
  SECRET_KEY: "<your-secret-key>"
  DJANGO_SETTINGS_MODULE: {{ .Values.application.djangoSetting | quote }}
  STATIC_URL: {{ .Values.application.staticURL | quote }}
  FORCE_SCRIPT_NAME: {{ .Values.application.basePath | quote }}
  SENTRY_ENABLED: {{ .Values.application.enableSentry | quote }}
  SENTRY_DSN: {{ .Values.application.sentryDSN | quote }}

  # DB Settings
  DB_HOST: {{ .Values.db.postgresql.dbHost | quote }}
  DB_NAME: {{ .Values.db.postgresql.dbName | quote }}
  DB_USER: {{ .Values.db.postgresql.dbUser | quote }}
  REDIS_HOST: {{ .Values.db.redis.dbHost | quote }}
